### PR TITLE
fix flakes in log following related unit tests

### LINKED ISSUE #103: Flaky Unit Test Results
### `TestStartBuildRunFollowLog` (`pkg/shp/cmd/build`)

```bash
for i in `seq 1 100` ; do 
	echo "# Attempt ${i}..."
	make test-unit \
		GO_FLAGS='' \
		GO_TEST_FLAGS='-race -failfast -timeout=45s' \
		CMD='' \
		PKG=./pkg/shp/cmd/build \
		ARGS='-run="^TestStartBuildRunFollowLog"' || break
done
```

Fails after a few attempts:

```
# Attempt 1...
go test  -race -failfast -timeout=45s  ./pkg/shp/cmd/build -run="^TestStartBuildRunFollowLog"
ok      github.com/shipwright-io/cli/pkg/shp/cmd/build  20.195s
# Attempt 2...
go test  -race -failfast -timeout=45s  ./pkg/shp/cmd/build -run="^TestStartBuildRunFollowLog"
ok      github.com/shipwright-io/cli/pkg/shp/cmd/build  21.195s
# Attempt 3...
go test  -race -failfast -timeout=45s  ./pkg/shp/cmd/build -run="^TestStartBuildRunFollowLog"
ok      github.com/shipwright-io/cli/pkg/shp/cmd/build  21.195s
# Attempt 4...
go test  -race -failfast -timeout=45s  ./pkg/shp/cmd/build -run="^TestStartBuildRunFollowLog"
[container] fake logs
panic: test timed out after 45s
```

### `Test_PodWatcherEvents` (`pkg/shp/reactor`)

```bash
make test-unit \
	GO_TEST_FLAGS='-race -cover -failfast' \
	CMD='' \
	PKG=./pkg/shp/reactor \
	ARGS='-run="^Test_PodWatcherEvents"'
```

Running the same test a few times sequentially, ends up as the following:

```
go test -v -mod=vendor -race -cover -failfast  ./pkg/shp/reactor -run="^Test_PodWatcherEvents"
=== RUN   Test_PodWatcherEvents
=== RUN   Test_PodWatcherEvents/pod-is-added
=== RUN   Test_PodWatcherEvents/pod-is-modified
=== RUN   Test_PodWatcherEvents/pod-is-deleted
=== CONT  Test_PodWatcherEvents
    pod_watcher_test.go:234:
        Timed out after 10.001s.
        Expected
            <chan string | len:0, cap:5>: 0xc000444180
        to receive something.
--- FAIL: Test_PodWatcherEvents (10.00s)
    --- PASS: Test_PodWatcherEvents/pod-is-added (0.00s)
    --- PASS: Test_PodWatcherEvents/pod-is-modified (0.00s)
    --- PASS: Test_PodWatcherEvents/pod-is-deleted (0.00s)
FAIL
coverage: 59.1% of statements
FAIL    github.com/shipwright-io/cli/pkg/shp/reactor    10.038s
FAIL
make: *** [Makefile:60: test-unit] Error 1
```

### PR DESCRIPTION
**Pull request by gabemontero**
# Changes

Fixes #103

/kind cleanup

Hello @otaviof @HeavyWombat @SaschaSchwarze0 

I *finally* got some shipwright cycles this week, and one of my long standing to-do's was to spend quality time on the log following unit test flakes @otaviof reported.

Allow me to explain my process to getting to this point of an alternative PR.

While, as it is clear to see, I initially took a brief pass at reviewing @otaviof 's #104 a month ago, I decided to re-engage here by first making sure I understood first hand what was the crux of the original situation as I remember @otaviof describing in our team meetings, where if I were to attempt to summarize, it was the inherent fragility of k8s fake clients, especially around watches (of course @otaviof please do chime in if my brief summary misses key points).

So running @otaviof 's reproducers in #103 as well as running the unit tests in the debugger, the k8s fake client watch fragility is what was most noticeable to me.  If I were to attempt to summarize, it did not seem thread safe.  To the point where it was unclear if the events reported by the unit test as missing were the actual events that were missing.

But even of more importance, the "has synced" concept we have with the k8s watch based informers used in controllers occurred to me as being something that would be useful here (I describe this in more detail in https://github.com/shipwright-io/cli/issues/103#issuecomment-1103224373).  So, building on that to see if that proved valid (which it did), after about a full day of coding, I've got a different take on addressing this flake with this PR.

I see #104 needs a rebase as it its.  My initial thought is we iterate on this to merge it, so we address the flake. Then reset and see if we want some of the refactoring from #104 that may not be *immediately* related to the k8s fake client flakiness, but that we like,  either by reworking 1#04, and get that ready again, or if it makes sense to just redo #104 in a new PR.  But that said, if folks think of elements of #104 that can be easily applied here, sure, let's discuss.

A more detailed breakdown
- no changes to the existing flags ... the "user experience" is the same 
- follwer/pod_watcher `Start` methonds have been split into `Connect` and `WaitForCompletion` ... this somewhat speaks to the "has synched" concept with k8s informers
- the run command has a `FollowerReady` method to help with multi-threaded use of consumers of the follower (in theory other commands that use follower could follow this pattern if need be) ... this more directly is the "has synched" equivalent from k8s informers
- we have better consistency across the different commands, in that they create or initialize their `Follwers` in their `Complete` methods, and they startup and wait for them in their `Run` methods
- removed the 3 second sleep in the follower event processing
- removed that initialization of the follower in the run unit test 
- added lower level tuning (not exposed as flags at this time) around some of the timing intervals to help speed up unit tests
- removed some of the multi threaded elements in the pod_watcher unit tests; they intermittently stressed the more flaky elements of the k8s fake clients, especially the watch elements; I think in the end, running with race detection, we have sufficient coverage there anyway

Some output from some of @otaviof 's flake reproducers:

```
# Attempt 97...
go test  -race -failfast -timeout=45s  ./pkg/shp/cmd/build -run="^TestStartBuildRunFollowLog"
ok  	github.com/shipwright-io/cli/pkg/shp/cmd/build	0.103s
# Attempt 98...
go test  -race -failfast -timeout=45s  ./pkg/shp/cmd/build -run="^TestStartBuildRunFollowLog"
ok  	github.com/shipwright-io/cli/pkg/shp/cmd/build	0.110s
# Attempt 99...
go test  -race -failfast -timeout=45s  ./pkg/shp/cmd/build -run="^TestStartBuildRunFollowLog"
ok  	github.com/shipwright-io/cli/pkg/shp/cmd/build	0.103s
# Attempt 100...
go test  -race -failfast -timeout=45s  ./pkg/shp/cmd/build -run="^TestStartBuildRunFollowLog"
ok  	github.com/shipwright-io/cli/pkg/shp/cmd/build	0.104s
gmontero ~/go/src/github.com/shipwright-io/cli-1  (k8s-unit-test-flake-impacts-podwatcher)$
```

# Submitter Checklist

- [/ ] Includes tests if functionality changed/was added
- [ n/a] Includes docs if changes are user-facing
- [ /] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [ /] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/main/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by gabemontero** [comment]
clean tests

saw one minor correction in the code  ... forgot to use the new fail poll interval in follow.go

**Comment by gabemontero** [comment]
fyi @otaviof @HeavyWombat @SaschaSchwarze0 - another simplification occurred to me last night

I'm making an update this morning and will post again if it is in fact successful and I've updated this PR

thanks

**Comment by gabemontero** [comment]
> fyi @otaviof @HeavyWombat @SaschaSchwarze0 - another simplification occurred to me last night
> 
> I'm making an update this morning and will post again if it is in fact successful and I've updated this PR
> 
> thanks

ok @otaviof @HeavyWombat @SaschaSchwarze0 my simplifications are in (along with some additional comments in the code explaining some details wrt mulit-threaded testing, or lack there of)

PTAL when you all get the chance

thanks

**Comment by gabemontero** [comment]
ok we all discussed this one in the community meeting

@otaviof is good with moving forward with this reduced scope version of addressing the test flakes.   He'll review, and when he and I iterate and land with consensus on these changes, we'll merge this.  @HeavyWombat and @SaschaSchwarze0 signed off on this plan as well.

going ahead and 

/approve

**Comment by otaviof** [comment]
On the very first run, it failed with test timeout, as per:

```
$ for i in `seq 1 100` ; do
        echo "# Attempt ${i}..."
        make test-unit \
                GO_FLAGS='' \
                GO_TEST_FLAGS='-race -failfast -timeout=45s' \
                CMD='' \
                PKG=./pkg/shp/cmd/build \
                ARGS='-run="^TestStartBuildRunFollowLog"' || break
done
# Attempt 1...
go test  -race -failfast -timeout=45s  ./pkg/shp/cmd/build -run="^TestStartBuildRunFollowLog"
[container] fake logs
panic: test timed out after 45s

goroutine 84 [running]:
testing.(*M).startAlarm.func1()
	/opt/homebrew/Cellar/go/1.18.1/libexec/src/testing/testing.go:2029 +0xb8
created by time.goFunc
	/opt/homebrew/Cellar/go/1.18.1/libexec/src/time/sleep.go:176 +0x4c

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000582340, {0x106c1e0de, 0x1a}, 0x1074a15e0)
	/opt/homebrew/Cellar/go/1.18.1/libexec/src/testing/testing.go:1487 +0x580
testing.runTests.func1(0x0?)
	/opt/homebrew/Cellar/go/1.18.1/libexec/src/testing/testing.go:1839 +0x98
testing.tRunner(0xc000582340, 0xc0007bfb98)
	/opt/homebrew/Cellar/go/1.18.1/libexec/src/testing/testing.go:1439 +0x190
testing.runTests(0xc0004595e0?, {0x108421bd0, 0x1, 0x1}, {0xc0004f7ce0?, 0x104f80a80?, 0x108451c80?})
	/opt/homebrew/Cellar/go/1.18.1/libexec/src/testing/testing.go:1837 +0x6cc
testing.(*M).Run(0xc0004595e0)
	/opt/homebrew/Cellar/go/1.18.1/libexec/src/testing/testing.go:1719 +0x87c
main.main()
	_testmain.go:47 +0x300

goroutine 21 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x0?)
	/Users/otaviof/go/src/github.com/shipwright-io/cli/vendor/k8s.io/klog/v2/klog.go:1283 +0x78
created by k8s.io/klog/v2.init.0
	/Users/otaviof/go/src/github.com/shipwright-io/cli/vendor/k8s.io/klog/v2/klog.go:420 +0x20c

goroutine 5 [chan receive]:
knative.dev/pkg/metrics.(*metricsWorker).start(0xc000010258)
	/Users/otaviof/go/src/github.com/shipwright-io/cli/vendor/knative.dev/pkg/metrics/metrics_worker.go:99 +0x48
created by knative.dev/pkg/metrics.init.0
	/Users/otaviof/go/src/github.com/shipwright-io/cli/vendor/knative.dev/pkg/metrics/exporter.go:39 +0x138

goroutine 39 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0001fe000)
	/Users/otaviof/go/src/github.com/shipwright-io/cli/vendor/go.opencensus.io/stats/view/worker.go:276 +0x104
created by go.opencensus.io/stats/view.init.0
	/Users/otaviof/go/src/github.com/shipwright-io/cli/vendor/go.opencensus.io/stats/view/worker.go:34 +0xfc

goroutine 6 [select]:
github.com/shipwright-io/cli/pkg/shp/reactor.(*PodWatcher).Start(0xc000550300, {{{0x0, 0x0}, {0x0, 0x0}}, {0xc000138460, 0x44}, {0x0, 0x0}, 0x0, ...})
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/reactor/pod_watcher.go:133 +0x318
github.com/shipwright-io/cli/pkg/shp/cmd/follower.(*Follower).Start(...)
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/cmd/follower/follow.go:239
github.com/shipwright-io/cli/pkg/shp/cmd/build.(*RunCommand).Run(0xc000066d40, 0x1074c5f10?, 0xc000532810)
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/cmd/build/run.go:111 +0x48c
github.com/shipwright-io/cli/pkg/shp/cmd/build.TestStartBuildRunFollowLog(0xc0005824e0)
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/cmd/build/run_test.go:191 +0x1498
testing.tRunner(0xc0005824e0, 0x1074a15e0)
	/opt/homebrew/Cellar/go/1.18.1/libexec/src/testing/testing.go:1439 +0x190
created by testing.(*T).Run
	/opt/homebrew/Cellar/go/1.18.1/libexec/src/testing/testing.go:1486 +0x564

goroutine 25 [select]:
github.com/shipwright-io/cli/pkg/shp/reactor.(*PodWatcher).Start(0xc000550000, {{{0x0, 0x0}, {0x0, 0x0}}, {0xc00047e050, 0x44}, {0x0, 0x0}, 0x0, ...})
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/reactor/pod_watcher.go:133 +0x318
github.com/shipwright-io/cli/pkg/shp/cmd/follower.(*Follower).Start(...)
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/cmd/follower/follow.go:239
github.com/shipwright-io/cli/pkg/shp/cmd/build.(*RunCommand).Run(0xc0000666c0, 0x106c82150?, 0xc00053c360)
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/cmd/build/run.go:111 +0x48c
github.com/shipwright-io/cli/pkg/shp/cmd/build.TestStartBuildRunFollowLog.func3()
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/cmd/build/run_test.go:197 +0x54
created by github.com/shipwright-io/cli/pkg/shp/cmd/build.TestStartBuildRunFollowLog
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/cmd/build/run_test.go:196 +0x1600

goroutine 10 [select]:
github.com/shipwright-io/cli/pkg/shp/reactor.(*PodWatcher).Start(0xc00052a900, {{{0x0, 0x0}, {0x0, 0x0}}, {0xc000138230, 0x44}, {0x0, 0x0}, 0x0, ...})
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/reactor/pod_watcher.go:133 +0x318
github.com/shipwright-io/cli/pkg/shp/cmd/follower.(*Follower).Start(...)
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/cmd/follower/follow.go:239
github.com/shipwright-io/cli/pkg/shp/cmd/build.(*RunCommand).Run(0xc000112640, 0x106c82150?, 0xc000533230)
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/cmd/build/run.go:111 +0x48c
github.com/shipwright-io/cli/pkg/shp/cmd/build.TestStartBuildRunFollowLog.func3()
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/cmd/build/run_test.go:197 +0x54
created by github.com/shipwright-io/cli/pkg/shp/cmd/build.TestStartBuildRunFollowLog
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/cmd/build/run_test.go:196 +0x1600

goroutine 12 [chan receive]:
github.com/shipwright-io/cli/pkg/shp/tail.(*Tail).Start.func1.1()
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/tail/tail.go:54 +0x5c
created by github.com/shipwright-io/cli/pkg/shp/tail.(*Tail).Start.func1
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/tail/tail.go:53 +0x27c

goroutine 32 [select]:
github.com/shipwright-io/cli/pkg/shp/reactor.(*PodWatcher).Start(0xc000550180, {{{0x0, 0x0}, {0x0, 0x0}}, {0xc000a481e0, 0x44}, {0x0, 0x0}, 0x0, ...})
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/reactor/pod_watcher.go:133 +0x318
github.com/shipwright-io/cli/pkg/shp/cmd/follower.(*Follower).Start(...)
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/cmd/follower/follow.go:239
github.com/shipwright-io/cli/pkg/shp/cmd/build.(*RunCommand).Run(0xc0004bf4c0, 0x106c82150?, 0xc00069d590)
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/cmd/build/run.go:111 +0x48c
github.com/shipwright-io/cli/pkg/shp/cmd/build.TestStartBuildRunFollowLog.func3()
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/cmd/build/run_test.go:197 +0x54
created by github.com/shipwright-io/cli/pkg/shp/cmd/build.TestStartBuildRunFollowLog
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/cmd/build/run_test.go:196 +0x1600

goroutine 82 [chan receive (nil chan)]:
github.com/shipwright-io/cli/pkg/shp/tail.(*Tail).Start.func2()
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/tail/tail.go:65 +0x54
created by github.com/shipwright-io/cli/pkg/shp/tail.(*Tail).Start
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/tail/tail.go:64 +0x1d8
FAIL	github.com/shipwright-io/cli/pkg/shp/cmd/build	45.740s
FAIL
make: *** [test-unit] Error 1
```

**Comment by gabemontero** [comment]
very weird ... I ran that for loop a bunch of times 

either I made a minor change that messed things up and forgot to run the for loop, or this flake is really intermittent

ok I'll take another pass today and report back

thanks

**Comment by gabemontero** [comment]
@otaviof - are you sure you recompiled with my branch?  The line numbers from your https://github.com/shipwright-io/cli/pull/112#issuecomment-1111762739 do not line up with what I see in the code.

As an example:

```
goroutine 6 [select]:
github.com/shipwright-io/cli/pkg/shp/reactor.(*PodWatcher).Start(0xc000550300, {{{0x0, 0x0}, {0x0, 0x0}}, {0xc000138460, 0x44}, {0x0, 0x0}, 0x0, ...})
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/reactor/pod_watcher.go:133 +0x318
github.com/shipwright-io/cli/pkg/shp/cmd/follower.(*Follower).Start(...)
	/Users/otaviof/go/src/github.com/shipwright-io/cli/pkg/shp/cmd/follower/follow.go:239
```

When I look at the code, the `Start` in follow.go starts on line 274.

And line 133 of pod_watcher.go is a comment.  The select actually starts on line 137 for me.


The line numbers in your stack traces do line up with what I see in main branch.

**Comment by gabemontero** [comment]
Just ran 

```
for i in `seq 1 100` ; do
        echo "# Attempt ${i}..."
        make test-unit \
                GO_FLAGS='' \
                GO_TEST_FLAGS='-race -failfast -timeout=45s' \
                CMD='' \
                PKG=./pkg/shp/cmd/build \
                ARGS='-run="^TestStartBuildRunFollowLog"' || break
done
```

and it completes OK for me:

```
# Attempt 98...
go test  -race -failfast -timeout=45s  ./pkg/shp/cmd/build -run="^TestStartBuildRunFollowLog"
ok  	github.com/shipwright-io/cli/pkg/shp/cmd/build	0.104s
# Attempt 99...
go test  -race -failfast -timeout=45s  ./pkg/shp/cmd/build -run="^TestStartBuildRunFollowLog"
ok  	github.com/shipwright-io/cli/pkg/shp/cmd/build	0.105s
# Attempt 100...
go test  -race -failfast -timeout=45s  ./pkg/shp/cmd/build -run="^TestStartBuildRunFollowLog"
ok  	github.com/shipwright-io/cli/pkg/shp/cmd/build	0.104s
```

**Comment by otaviof** [comment]
> @otaviof - are you sure you recompiled with my branch? The line numbers from your [#112 (comment)](https://github.com/shipwright-io/cli/pull/112#issuecomment-1111762739) do not line up with what I see in the code.
> [...]

Sorry 🤦‍♀️ I end up running the tests on the wrong terminal window. Indeed, the tests are passing consistently, so I'll continue the review where I left this morning 👍

**Comment by gabemontero** [comment]
> > @otaviof - are you sure you recompiled with my branch? The line numbers from your [#112 (comment)](https://github.com/shipwright-io/cli/pull/112#issuecomment-1111762739) do not line up with what I see in the code.
> > [...]
> 
> Sorry woman_facepalming I end up running the tests on the wrong terminal window. Indeed, the tests are passing consistently, so I'll continue the review where I left this morning +1

whew :-) ... great thanks for confirming @otaviof

File: pkg/shp/reactor/pod_watcher.go [hunk 1]
```diff
@@ -120,15 +120,19 @@ func (p *PodWatcher) handleEvent(pod *corev1.Pod, event watch.Event) error {
 	return nil
 }
 
-// Start runs the event loop based on a watch instantiated against informed pod. In case of errors
-// the loop is interrupted.
-func (p *PodWatcher) Start(listOpts metav1.ListOptions) (*corev1.Pod, error) {
+func (p *PodWatcher) Connect(listOpts metav1.ListOptions) error {
```
Comment (otaviof) [inline pkg/shp/reactor/pod_watcher.go:123]: Would be great to add a doc-comment explaining how the connect helps the multi-threading, etc.

File: pkg/shp/cmd/build/run.go [hunk 2]
```diff
@@ -27,6 +27,7 @@ type RunCommand struct {
 	buildRunSpec *buildv1alpha1.BuildRunSpec // stores command-line flags
 	follow       bool                        // flag to tail pod logs
 	follower     *follower.Follower
+	follwerReady chan bool
```
Comment (otaviof) [inline pkg/shp/cmd/build/run.go:30]: nit: typo on the variable name.

**Review by otaviof — COMMENTED** [review]
@gabemontero Just a couple of "nit" comments, all in all I liked the approach to avoid flaky results and reliably consume `Watch` events 👍  Thanks!

**Comment by otaviof** [comment]
/lgtm

Thanks @gabemontero!
