### PR TITLE
Fix local source build

### LINKED ISSUE #332: [BUG] nil pointer dereference when using local source build with 0.16 CLI
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Kubernetes Version

_No response_

### Shipwright Version

v0.16

### Current Behavior

```
➜  temp bash builds.sh
Flag --dockerfile has been deprecated, dockerfile parameter is deprecated
ERROR: builds.shipwright.io "sample-python-buildah-1-0" already exists
2025/07/15 17:35:15 Creating a BuildRun for 'builds/sample-python-buildah-1-0' Build...
2025/07/15 17:35:16 BuildRun 'sample-python-buildah-1-0-qhbfk' created!
Pod "sample-python-buildah-1-0-qhbfk-2vjfk-pod" is in state "Pending"...
Pod "sample-python-buildah-1-0-qhbfk-2vjfk-pod" is in state "Pending"...
Pod "sample-python-buildah-1-0-qhbfk-2vjfk-pod" is in state "Pending"...
Pod "sample-python-buildah-1-0-qhbfk-2vjfk-pod" in "Running" state, starting up log tail
Streaming "/home/avinal/Documents/redhat/github.com/temp/cust" to the Build POD "sample-python-buildah-1-0-qhbfk-2
Uploading local source... 100% [===============] (499 GB/s)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1eaca25]

goroutine 1 [running]:
github.com/shipwright-io/cli/pkg/shp/streamer.(*Streamer).Stream(0x0, 0xc000ee7748, 0xc000da81a0, 0xa9200)
        github.com/shipwright-io/cli/pkg/shp/streamer/streamer.go:101 +0x545
github.com/shipwright-io/cli/pkg/shp/cmd/build.(*UploadCommand).performDataStreaming(0xc00017f180, 0xc000ee7748)
        github.com/shipwright-io/cli/pkg/shp/cmd/build/upload.go:223 +0x19e
github.com/shipwright-io/cli/pkg/shp/cmd/build.(*UploadCommand).onPodModifiedEventStreaming(0xc00017f180, 0xc0004a7b08?)
        github.com/shipwright-io/cli/pkg/shp/cmd/build/upload.go:251 +0x1b6
github.com/shipwright-io/cli/pkg/shp/reactor.(*PodWatcher).handleEvent(0xc0003f5380?, 0xc0004a7b08, {{0xc00087a8e8?, 0x0?}, {0x2a195b8?, 0xc0004a7b08?}})
        github.com/shipwright-io/cli/pkg/shp/reactor/pod_watcher.go:107 +0x148
github.com/shipwright-io/cli/pkg/shp/reactor.(*PodWatcher).WaitForCompletion(0xc0003f5380)
        github.com/shipwright-io/cli/pkg/shp/reactor/pod_watcher.go:162 +0x4a6
github.com/shipwright-io/cli/pkg/shp/reactor.(*PodWatcher).Start(0xc0003f5380, {{{0x0, 0x0}, {0x0, 0x0}}, {0xc000a965b0, 0x6e}, {0x0, 0x0}, 0x0, ...})
        github.com/shipwright-io/cli/pkg/shp/reactor/pod_watcher.go:213 +0x68
github.com/shipwright-io/cli/pkg/shp/cmd/build.(*UploadCommand).Run(0xc00017f180, 0xc00011f500, 0xc000423380)
        github.com/shipwright-io/cli/pkg/shp/cmd/build/upload.go:322 +0x445
github.com/shipwright-io/cli/pkg/shp/cmd/runner.(*Runner).RunE(0xc000420780, 0xc00077db40?, {0xc00011fbc0?, 0x0?, 0x0?})
        github.com/shipwright-io/cli/pkg/shp/cmd/runner/runner.go:35 +0x7f
github.com/spf13/cobra.(*Command).execute(0xc0001ba908, {0xc00011fb60, 0x6, 0x6})
        github.com/spf13/cobra@v1.9.1/command.go:1015 +0xa94
github.com/spf13/cobra.(*Command).ExecuteC(0x3ed1680)
        github.com/spf13/cobra@v1.9.1/command.go:1148 +0x40c
github.com/spf13/cobra.(*Command).Execute(0xc000423380?)
        github.com/spf13/cobra@v1.9.1/command.go:1071 +0x13
main.main()
        ./main.go:46 +0x125
```

### Expected Behavior

There should be no nil pointer dereference or segmentation fault.

### Steps To Reproduce

I am using local source build. Here are the Files

```bash
#!/bin/bash
BUILD_NAME="sample-python-buildah-1-0"
BUILD_NAMESPACE="test"
OUTPUT_IMAGE="ttl.sh/sample-python-builah:1h"
SOURCE_DIR="/home/avinal/Documents/redhat/github.com/temp/samples/buildpack"
SOURCE_PATH="platforms/paas/shared/artifacts/ms2ms/ms1"
# Create Build
shp build create $BUILD_NAME \
--namespace="$BUILD_NAMESPACE" \
--request-timeout="10m" \
--strategy-kind="ClusterBuildStrategy" \
--strategy-name="buildah" \
--dockerfile="Dockerfile" \
--output-image="$OUTPUT_IMAGE" \
--retention-failed-limit=5 \
--retention-succeeded-limit=10
# Upload Source
shp build upload ${BUILD_NAME} $SOURCE_DIR --follow \
--buildref-name="$BUILD_NAME" \
--namespace="$BUILD_NAMESPACE" \
--output-image="$OUTPUT_IMAGE" 
```

```dockerfile
FROM python:3.11-slim
COPY requirements.txt server.py vendor/ /usr/src/app/
RUN pip install -r /usr/src/app/requirements.txt --no-index --find-links file:///usr/src/app/vendor
WORKDIR /usr/src/app
EXPOSE 8080
ENTRYPOINT ["python3", "server.py"]
```

### Anything else?

This issue doesn't happen with 0.15 CLI.

### LINKED ISSUE #338: [BUG] Cannot change ownership to uid xx, gid xx: Operation not permitted from "tar" libraries
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Kubernetes Version

_No response_

### Shipwright Version

v0.16

### Current Behavior

While doing a local source build, the CLI throws the following error and the build fails.

```
2025/08/26 03:33:28 Creating a BuildRun for 'test/sample-buildah' Build...
2025/08/26 03:33:28 BuildRun 'sample-buildah-xfqpd' created!
Pod "sample-buildah-xfqpd-4jfmb-pod" is in state "Pending"...
Pod "sample-buildah-xfqpd-4jfmb-pod" is in state "Pending"...
Pod "sample-buildah-xfqpd-4jfmb-pod" is in state "Pending"...
Pod "sample-buildah-xfqpd-4jfmb-pod" is in state "Pending"...
Pod "sample-buildah-xfqpd-4jfmb-pod" in "Running" state, starting up log tail
Streaming "/Users/sayan/code/github.com/redhat-openshift-builds/samples/buildah" to the Build POD "sample-buildah-xfqpd-4jfmb-pod" ...
[prepare] 2025/08/25 22:03:29 Entrypoint initialization

Uploading local source... 100% [===============] (4.6 MB/s) tar: Dockerfile: Cannot change ownership to uid 501, gid 20: Operation not permitted
tar: entitled/Dockerfile: Cannot change ownership to uid 501, gid 20: Operation not permitted
tar: go.mod: Cannot change ownership to uid 501, gid 20: Operation not permitted
tar: main.go: Cannot change ownership to uid 501, gid 20: Operation not permitted
tar: Exiting with failure status due to previous errors
ERROR: command terminated with exit code 2
```

### Expected Behavior

The build should successfully complete.

### Steps To Reproduce

1. Install Shipwright in Kind or Minikube cluster
2. Install delivered cluster build strategies
3. Install Shipwright CLI
4. Create a `Build` with local source
```
shp build create sample-buildah \
--namespace="$BUILD_NAMESPACE" \
--request-timeout="10m" \
--strategy-kind="ClusterBuildStrategy" \
--strategy-name="buildah" \
--dockerfile="Dockerfile" \
--output-image="$OUTPUT_IMAGE" \
--retention-failed-limit=5 \
--retention-succeeded-limit=10
Created build "sample-buildah"
```
5. Run build using shipwright CLI
```
shp build upload \                                                     
"$BUILD_NAME" \
"$SOURCE_DIR" --follow \
--namespace="$BUILD_NAMESPACE" \
--output-image="$OUTPUT_IMAGE"
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sayan-biswas**
# Changes
- Data stream was only being initialized when the source is not OCI artifact. Hence, in cases where the source itself is not specified in the Build object, the struct was left uninitialized
- Explicitly set UID and GID to 0 in "tar" header while writing archive, to prevent permission issue with local file having different UID and GID

Fixes #332 
Fixes #338 

# Submitter Checklist

- [ ] Includes tests if functionality changed/was added
- [ ] Includes docs if changes are user-facing
- [x] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)
- [x] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/main/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes

```release-note
Fixes bugs with builds from local source code
```

### CODE REVIEW

File: pkg/shp/cmd/build/upload.go [hunk 1]
```diff
@@ -120,6 +120,9 @@ func (u *UploadCommand) Complete(p *params.Params, _ *genericclioptions.IOStream
 		return err
 	}
 
+	// Stream can be initialized irrespective of the Build source type
+	u.dataStreamer = streamer.NewStreamer(restConfig, clientset)
+
```
Comment (rxinui) [inline pkg/shp/cmd/build/upload.go:125]: I'd move down to line 126 and remove the comment `// Stream can be initialized irrespective of the Build source type` as it does not _help_ the codebase but ease the current PR review...

**Review by rxinui — CHANGES_REQUESTED** [review]
Little comments regarding the changes
