### PR TITLE
various run build -F/--follow fixes around timeout, lack of pods, and data races

### LINKED ISSUE #53: shp build run --follow hangs if BuildRun fails to start
`shp build run --follow` is my favorite command, but, it actually hangs if a pod never gets created. It should also watch the BuildRun status. If that completes with a failure, then it should also return.

### PR DESCRIPTION
**Pull request by gabemontero**
# Changes

Fixes #53
- adds/tweaks integration from k8s `--request-timeout` and `--context` options that `shp` inherits from k8s to apply request or context deadline timeout / aborts on `ship build run --follow`
- add callbacks for lack of pod events, including cross reference with build run when those occur, just as we do when pod events do occur (still no explicit buildrun watch to go with pod watch, as multiple watches proves untenable with unit testing, plus over-indulgent, as we only need buildrun for terminal states), to exit --follow
- slight refactor of SubCommand interface to allow for more initialization in Complete() vs. Run() for --follow
- which allowed vast simplification of data race prevention on RunCommand
- and removal of what proved to be kludgy thread coordination in --follow unit tests

# Submitter Checklist

- [ /] Includes tests if functionality changed/was added
- [n/a ] Includes docs if changes are user-facing
- [ /] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [/ ] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/main/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

/kind bug

# Release Notes

```release-note
fully integrate options '--context' and '--request-timeout' into 'shp build run --follow' 
allow for exit if the underlying Pod for a BuildRun is never created
concurrency fixes
```

@adambkaplan 
@coreydaley 
@SaschaSchwarze0 
@otaviof

### CODE REVIEW

**Comment by gabemontero** [comment]
manual e2e test ... I'll see about adding an e2e test using our new bats based framework

```
gmontero ~/go/src/github.com/shipwright-io/cli-1  (fix-follow-no-pod)$ shp build run buildpack-nodejs-build -F
Pod 'buildpack-nodejs-build-l5hc6-9vllp-pod-thsfd' is in state "Pending"...
Pod 'buildpack-nodejs-build-l5hc6-9vllp-pod-thsfd' is in state "Pending"...
Pod 'buildpack-nodejs-build-l5hc6-9vllp-pod-thsfd' is in state "Pending"...
[place-tools] 2021/10/09 13:25:36 Copied /ko-app/entrypoint to /tekton/tools/entrypoint
[build-and-push] ===> DETECTING
[build-and-push] 5 of 9 buildpacks participating
[build-and-push] paketo-buildpacks/ca-certificates 2.4.1
[build-and-push] paketo-buildpacks/node-engine     0.8.0
[build-and-push] paketo-buildpacks/npm-install     0.4.0
[build-and-push] paketo-buildpacks/node-module-bom 0.1.2
[build-and-push] paketo-buildpacks/npm-start       0.4.0
[build-and-push] ===> ANALYZING
[source-default] 2021/10/09 13:25:38 Info: ssh (/usr/bin/ssh): OpenSSH_8.0p1, OpenSSL 1.1.1g FIPS  21 Apr 2020
[source-default] 2021/10/09 13:25:38 Info: git (/usr/bin/git): git version 2.27.0
[source-default] 2021/10/09 13:25:38 Info: git-lfs (/usr/bin/git-lfs): git-lfs/2.11.0 (GitHub; linux amd64; go 1.14.4)
[source-default] 2021/10/09 13:25:38 /usr/bin/git clone -h
[source-default] 2021/10/09 13:25:38 /usr/bin/git submodule -h
[source-default] 2021/10/09 13:25:38 /usr/bin/git clone --quiet --no-tags --single-branch --depth 1 -- https://github.com/shipwright-io/sample-nodejs /workspace/source
[source-default] 2021/10/09 13:25:38 /usr/bin/git -C /workspace/source submodule update --init --recursive --depth 1
[source-default] 2021/10/09 13:25:38 /usr/bin/git -C /workspace/source rev-parse --abbrev-ref HEAD
[source-default] 2021/10/09 13:25:38 Successfully loaded https://github.com/shipwright-io/sample-nodejs (main) into /workspace/source
[source-default] 2021/10/09 13:25:38 /usr/bin/git -C /workspace/source rev-parse --verify HEAD
[source-default] 2021/10/09 13:25:38 /usr/bin/git -C /workspace/source log -1 --pretty=format:%an
[build-and-push] Previous image with name "" not found
[build-and-push] Restoring metadata for "paketo-buildpacks/ca-certificates:helper" from app image
[build-and-push] ===> RESTORING
[build-and-push] ===> BUILDING
[build-and-push] 
[build-and-push] Paketo CA Certificates Buildpack 2.4.1
[build-and-push]   https://github.com/paketo-buildpacks/ca-certificates
[build-and-push]   Launch Helper: Reusing cached layer
[build-and-push] Paketo Node Engine Buildpack 0.8.0
[build-and-push]   Resolving Node Engine version
[build-and-push]     Candidate version sources (in priority order):
[build-and-push]       package.json -> ">= 0.10.12"
[build-and-push]       <unknown>    -> ""
[build-and-push] 
[build-and-push]     Selected Node Engine version (using package.json): 16.9.1
[build-and-push] 
[build-and-push]   Executing build process
[build-and-push]     Installing Node Engine 16.9.1
[build-and-push]       Completed in 2.796s
[build-and-push] 
[build-and-push]   Configuring build environment
[build-and-push]     NODE_ENV     -> "production"
[build-and-push]     NODE_HOME    -> "/layers/paketo-buildpacks_node-engine/node"
[build-and-push]     NODE_VERBOSE -> "false"
[build-and-push] 
[build-and-push]   Configuring launch environment
[build-and-push]     NODE_ENV     -> "production"
[build-and-push]     NODE_HOME    -> "/layers/paketo-buildpacks_node-engine/node"
[build-and-push]     NODE_VERBOSE -> "false"
[build-and-push] 
[build-and-push]     Writing profile.d/0_memory_available.sh
[build-and-push]       Calculates available memory based on container limits at launch time.
[build-and-push]       Made available in the MEMORY_AVAILABLE environment variable.
[build-and-push] 
[build-and-push] Paketo NPM Install Buildpack 0.4.0
[build-and-push]   Resolving installation process
[build-and-push]     Process inputs:
[build-and-push]       node_modules      -> "Not found"
[build-and-push]       npm-cache         -> "Not found"
[build-and-push]       package-lock.json -> "Not found"
[build-and-push] 
[build-and-push]     Selected NPM build process: 'npm install'
[build-and-push] 
[build-and-push]   Executing build process
[build-and-push]     Running 'npm install --unsafe-perm --cache /layers/paketo-buildpacks_npm-install/npm-cache'
[build-and-push]       Completed in 1.013s
[build-and-push] 
[build-and-push]   Configuring launch environment
[build-and-push]     NPM_CONFIG_LOGLEVEL -> "error"
[build-and-push] 
[build-and-push]   Configuring environment shared by build and launch
[build-and-push]     PATH -> "$PATH:/layers/paketo-buildpacks_npm-install/modules/node_modules/.bin"
[build-and-push] 
[build-and-push] 
[build-and-push] Paketo Node Module Bill of Materials Generator Buildpack 0.1.2
[build-and-push]   Resolving CycloneDX Node.js Module version
[build-and-push]     Selected CycloneDX Node.js Module version: 3.0.7
[build-and-push] 
[build-and-push]   Executing build process
[build-and-push]     Installing CycloneDX Node.js Module 3.0.7
[build-and-push]       Completed in 242ms
[build-and-push] 
[build-and-push]   Configuring environment
[build-and-push]     Appending CycloneDX Node.js Module onto PATH
[build-and-push] 
[build-and-push]   Running CycloneDX Node.js Module
[build-and-push]     Running 'cyclonedx-bom -o bom.json'
[build-and-push]       Completed in 236ms
[build-and-push] 
[build-and-push] Paketo NPM Start Buildpack 0.4.0
[build-and-push]   Assigning launch processes
[build-and-push]     web: node server.js
[build-and-push] 
[build-and-push] ===> EXPORTING
[build-and-push] Reusing layers from image 'index.docker.io/gmontero/sample-nodejs@sha256:1cabccf7ba39c8041e2563f43a1aa878ab6c98f085fcff3c5dfc9c436783564c'
[build-and-push] Reusing layer 'paketo-buildpacks/ca-certificates:helper'
[build-and-push] Reusing layer 'paketo-buildpacks/node-engine:node'
[build-and-push] Reusing layer 'paketo-buildpacks/npm-install:modules'
[build-and-push] Reusing 1/1 app layer(s)
[build-and-push] Reusing layer 'launcher'
[build-and-push] Reusing layer 'config'
[build-and-push] Adding label 'io.buildpacks.lifecycle.metadata'
[build-and-push] Adding label 'io.buildpacks.build.metadata'
[build-and-push] Adding label 'io.buildpacks.project.metadata'
[build-and-push] Saving docker.io/gmontero/sample-nodejs:latest...
[build-and-push] *** Images (sha256:9da0768da7a03aeef6e06d42f833e9772e5d07cae9d8ebccb79e75204584922e):
[build-and-push]       docker.io/gmontero/sample-nodejs:latest
[build-and-push] Adding cache layer 'paketo-buildpacks/node-engine:node'
[build-and-push] Adding cache layer 'paketo-buildpacks/npm-install:modules'
[build-and-push] Adding cache layer 'paketo-buildpacks/node-module-bom:cyclonedx-node-module'
Pod 'buildpack-nodejs-build-l5hc6-9vllp-pod-thsfd' has succeeded!
gmontero ~/go/src/github.com/shipwright-io/cli-1  (fix-follow-no-pod)$ 
```

**Comment by gabemontero** [comment]
meets min e2e added

note the TODO / item for follow up, unless a reviewer has a quick/easy solution that I feel is suitable for this PR

File: pkg/shp/cmd/build/run.go [hunk 1]
```diff
@@ -92,11 +119,47 @@ func (r *RunCommand) tailLogs(pod *corev1.Pod) {
...
+			msg = fmt.Sprintf("BuildRun '%s' has been canceled.\n", br.Name)
+		case br.DeletionTimestamp != nil:
+			giveUp = true
+			msg = fmt.Sprintf("BuildRun '%s' has been deleted.\n", br.Name)
+		case !br.HasStarted():
+			r.Log(fmt.Sprintf("BuildRun '%s' has been marked as failed.\n", br.Name))
+		}
+		if giveUp {
+			r.Log(msg)
+			r.Log(fmt.Sprintf("exting 'ship build run --follow' for BuildRun %q", br.Name))
```
Comment (SaschaSchwarze0) [inline pkg/shp/cmd/build/run.go:150]:
```suggestion
			r.Log(fmt.Sprintf("exiting 'ship build run --follow' for BuildRun %q", br.Name))
```

File: pkg/shp/cmd/build/run.go [hunk 2]
```diff
@@ -92,11 +119,47 @@ func (r *RunCommand) tailLogs(pod *corev1.Pod) {
...
+			r.stop()
+		}
+	}
```
Comment (coreydaley) [inline pkg/shp/cmd/build/run.go:153]:
```suggestion
	if err != nil {
		r.Log(fmt.Sprintf("error accessing BuildRun %q: %s", r.buildRunName, err.Error()))
		return
	}
	c := br.Status.GetCondition(buildv1alpha1.Succeeded)
	switch {
	case c != nil && c.Status == corev1.ConditionTrue:
		r.Log(fmt.Sprintf("BuildRun '%s' has been marked as successful.\n", br.Name))
		r.stop()
	case c != nil && c.Status == corev1.ConditionFalse:
		r.Log(fmt.Sprintf("BuildRun '%s' has been marked as failed.\n", br.Name))
		r.stop()
	case br.IsCanceled():
		r.Log(fmt.Sprintf("BuildRun '%s' has been canceled.\n", br.Name))
		r.stop()
	case br.DeletionTimestamp != nil:
		r.Log(fmt.Sprintf("BuildRun '%s' has been deleted.\n", br.Name))
		r.stop()
	case !br.HasStarted():
		r.Log(fmt.Sprintf("BuildRun '%s' has been marked as failed.\n", br.Name))
	}
```

I think that this is cleaner and easier to tell exactly what is going on instead of having to track to the end of the switch statement to see what happens.

Comment (gabemontero) [reply pkg/shp/cmd/build/run.go:153]: I agree

*maybe* in one of my iterations prior to push I had something after the else block, but there's no telling :-)

**Comment by gabemontero** [comment]
> > @gabemontero were you able to resolve the issues with the builds not succeeding?
> 
> yeah mean the new e2e's? No. And depending on the timing of the remaining items, I'm inclined to leave the e2e as is (since it can still verify the log is being followed, which is the key), and opening an issue to clean that up when someone has time to look into it.

opened https://github.com/shipwright-io/cli/issues/57 for ^^

**Review by SaschaSchwarze0 — APPROVED** [review]
/unhold
